include: package:lint/strict.yaml

analyzer:
  exclude: ['test/**', '**.g.dart', '**.freezed.dart']
  plugins:
    - riverpod_lint

plugins:
  riverpod_lint: 3.1.0

linter:
  rules:
    avoid_classes_with_only_static_members: false
    prefer_constructors_over_static_methods: false
