import 'dart:convert';

/// Represents an auto-generated monthly spending summary.
class MonthlySummary {
  /// Month in "YYYY-MM" format, e.g. "2026-02".
  final String month;

  /// Total amount spent during the month.
  final double totalSpent;

  /// Monthly overall budget target (0 = not set).
  final double budgetTarget;

  /// Total amount spent in the month before this one (for MoM comparison).
  final double previousMonthSpent;

  /// Spending broken down by category (category -> total).
  final Map<String, double> categoryBreakdown;

  /// Top recipients by total spending (recipient -> total), ordered desc.
  final Map<String, double> topRecipients;

  /// Natural language narrative generated by the LLM.
  final String narrative;

  /// When this summary was generated.
  final DateTime generatedAt;

  const MonthlySummary({
    required this.month,
    required this.totalSpent,
    required this.budgetTarget,
    required this.previousMonthSpent,
    required this.categoryBreakdown,
    required this.topRecipients,
    required this.narrative,
    required this.generatedAt,
  });

  Map<String, dynamic> toJson() => {
        'month': month,
        'totalSpent': totalSpent,
        'budgetTarget': budgetTarget,
        'previousMonthSpent': previousMonthSpent,
        'categoryBreakdown': categoryBreakdown,
        'topRecipients': topRecipients,
        'narrative': narrative,
        'generatedAt': generatedAt.toIso8601String(),
      };

  factory MonthlySummary.fromJson(Map<String, dynamic> json) => MonthlySummary(
        month: json['month'] as String,
        totalSpent: (json['totalSpent'] as num).toDouble(),
        budgetTarget: (json['budgetTarget'] as num).toDouble(),
        previousMonthSpent: (json['previousMonthSpent'] as num).toDouble(),
        categoryBreakdown: (json['categoryBreakdown'] as Map<String, dynamic>)
            .map((k, v) => MapEntry(k, (v as num).toDouble())),
        topRecipients: (json['topRecipients'] as Map<String, dynamic>)
            .map((k, v) => MapEntry(k, (v as num).toDouble())),
        narrative: json['narrative'] as String,
        generatedAt: DateTime.parse(json['generatedAt'] as String),
      );

  /// Encode to JSON string for SharedPreferences storage.
  String toJsonString() => jsonEncode(toJson());

  /// Decode from JSON string stored in SharedPreferences.
  static MonthlySummary fromJsonString(String s) =>
      MonthlySummary.fromJson(jsonDecode(s) as Map<String, dynamic>);
}
